In [46]:
#Importing Datascience Libararies 
import numpy as np
import pandas as pd

In [2]:
#Unloading the Data
Data = pd.read_csv("housing.csv")
Data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [3]:
#Seperating X Data and Y_Data
X_Data = Data.drop("median_house_value", axis=1)
y_Data = Data["median_house_value"]
X_Data, y_Data

(       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 0        -122.23     37.88                41.0        880.0           129.0
 1        -122.22     37.86                21.0       7099.0          1106.0
 2        -122.24     37.85                52.0       1467.0           190.0
 3        -122.25     37.85                52.0       1274.0           235.0
 4        -122.25     37.85                52.0       1627.0           280.0
 ...          ...       ...                 ...          ...             ...
 20635    -121.09     39.48                25.0       1665.0           374.0
 20636    -121.21     39.49                18.0        697.0           150.0
 20637    -121.22     39.43                17.0       2254.0           485.0
 20638    -121.32     39.43                18.0       1860.0           409.0
 20639    -121.24     39.37                16.0       2785.0           616.0

        population  households  median_income ocean_proximity
 0           322.0       126.0         8.3252        NEAR BAY
 1          2401.0      1138.0         8.3014        NEAR BAY
 2           496.0       177.0         7.2574        NEAR BAY
 3           558.0       219.0         5.6431        NEAR BAY
 4           565.0       259.0         3.8462        NEAR BAY
 ...           ...         ...            ...             ...
 20635       845.0       330.0         1.5603          INLAND
 20636       356.0       114.0         2.5568          INLAND
 20637      1007.0       433.0         1.7000          INLAND
 20638       741.0       349.0         1.8672          INLAND
 20639      1387.0       530.0         2.3886          INLAND

 [20640 rows x 9 columns],
 0        452600.0
 1        358500.0
 2        352100.0
 3        341300.0
 4        342200.0
            ...
 20635     78100.0
 20636     77100.0
 20637     92300.0
 20638     84700.0
 20639     89400.0
 Name: median_house_value, Length: 20640, dtype: float64)

In [4]:
#Filling the Incomplete Column with SimpleImputer and Dividing Data into training and testing
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
impute = SimpleImputer(fill_value=np.nan, strategy="mean")
Data.isnull().sum() 
X_train, X_test, y_train, y_test = train_test_split(X_Data, y_Data, test_size = 0.2, random_state = 1)

X_train["total_bedrooms"] = impute.fit_transform(X_train[["total_bedrooms"]])
X_test["total_bedrooms"] = impute.fit_transform(X_test[["total_bedrooms"]])

In [5]:
#Putting labels on the Catagorical Columns
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train["ocean_proximity"] = le.fit_transform(X_train["ocean_proximity"])
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
15961,-122.43,37.71,52.0,1410.0,286.0,879.0,282.0,3.1908,3
1771,-122.35,37.95,42.0,1485.0,290.0,971.0,303.0,3.6094,3
16414,-121.24,37.90,16.0,50.0,10.0,20.0,6.0,2.6250,1
5056,-118.35,34.02,34.0,5218.0,1576.0,3538.0,1371.0,1.5143,0
8589,-118.39,33.89,38.0,1851.0,332.0,750.0,314.0,7.3356,0
...,...,...,...,...,...,...,...,...,...
10955,-117.88,33.76,17.0,1768.0,474.0,1079.0,436.0,1.7823,0
17289,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,0
5192,-118.26,33.93,42.0,1433.0,295.0,775.0,293.0,1.1326,0
12172,-117.16,33.73,10.0,2381.0,454.0,1323.0,477.0,2.6322,1
235,-122.20,37.79,35.0,1802.0,459.0,1009.0,390.0,2.3036,3

In [6]:
                                                            #Exploratory Data Analysis
#Checking top 5 values
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
15961,-122.43,37.71,52.0,1410.0,286.0,879.0,282.0,3.1908,3
1771,-122.35,37.95,42.0,1485.0,290.0,971.0,303.0,3.6094,3
16414,-121.24,37.90,16.0,50.0,10.0,20.0,6.0,2.6250,1
5056,-118.35,34.02,34.0,5218.0,1576.0,3538.0,1371.0,1.5143,0
8589,-118.39,33.89,38.0,1851.0,332.0,750.0,314.0,7.3356,0

In [7]:
#Checking Bottom 5 Values
X_train.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
10955,-117.88,33.76,17.0,1768.0,474.0,1079.0,436.0,1.7823,0
17289,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,0
5192,-118.26,33.93,42.0,1433.0,295.0,775.0,293.0,1.1326,0
12172,-117.16,33.73,10.0,2381.0,454.0,1323.0,477.0,2.6322,1
235,-122.20,37.79,35.0,1802.0,459.0,1009.0,390.0,2.3036,3

In [21]:
X_train.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
count,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000
mean,-119.574288,35.632194,28.604469,2639.590661,539.049544,1425.257146,500.593508,3.876149,1.166303
std,2.007578,2.137087,12.586046,2176.421777,418.810986,1123.756792,382.439609,1.891584,1.423590
min,-124.300000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,0.000000
25%,-121.810000,33.930000,18.000000,1451.000000,297.000000,786.000000,279.000000,2.572050,0.000000
50%,-118.490000,34.260000,29.000000,2127.000000,438.000000,1164.000000,410.000000,3.544550,1.000000
75%,-118.010000,37.710000,37.000000,3149.000000,644.250000,1723.000000,605.250000,4.750000,1.000000
max,-114.310000,41.950000,52.000000,39320.000000,6210.000000,35682.000000,5358.000000,15.000100,4.000000

In [22]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16512 entries, 15961 to 235
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.3 MB

In [10]:
X_train.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
dtype: int64

In [11]:
#Dropping the Duplicate values 
X_train = X_train.drop_duplicates()
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
15961,-122.43,37.71,52.0,1410.0,286.0,879.0,282.0,3.1908,3
1771,-122.35,37.95,42.0,1485.0,290.0,971.0,303.0,3.6094,3
16414,-121.24,37.90,16.0,50.0,10.0,20.0,6.0,2.6250,1
5056,-118.35,34.02,34.0,5218.0,1576.0,3538.0,1371.0,1.5143,0
8589,-118.39,33.89,38.0,1851.0,332.0,750.0,314.0,7.3356,0
...,...,...,...,...,...,...,...,...,...
10955,-117.88,33.76,17.0,1768.0,474.0,1079.0,436.0,1.7823,0
17289,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,0
5192,-118.26,33.93,42.0,1433.0,295.0,775.0,293.0,1.1326,0
12172,-117.16,33.73,10.0,2381.0,454.0,1323.0,477.0,2.6322,1
235,-122.20,37.79,35.0,1802.0,459.0,1009.0,390.0,2.3036,3

In [12]:
#Performing PreProcessing on the Numerical Data 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, StandardScaler

ct = ColumnTransformer(
    transformers=[
        ("si", StandardScaler(), ["longitude", "latitude", "housing_median_age", "total_rooms", "total_bedrooms", "population", "households",	"median_income"])
    ])
X_train_final = ct.fit_transform(X_train)
X_test_final = ct.transform(X_test)
X_train_final, X_test_final

(array([[-1.42250942,  0.97229046,  1.85890297, ..., -0.4861138 ,
         -0.57159385, -0.36232605],
        [-1.38265919,  1.08459626,  1.06434823, ..., -0.40424308,
         -0.51668155, -0.14102329],
        [-0.8297373 ,  1.06119922, -1.0014941 , ..., -1.25053723,
         -1.29329827, -0.66144956],
        ...,
        [ 0.65468363, -0.79652586,  1.06434823, ..., -0.57866332,
         -0.54283026, -1.45044201],
        [ 1.20262424, -0.89011402, -1.47822694, ..., -0.09099855,
         -0.06169398, -0.65764311],
        [-1.30794002,  1.00972573,  0.50815991, ..., -0.37042691,
         -0.28918777, -0.83136525]]),
 array([[ 0.60487084, -0.73569355,  0.82598181, ..., -0.28143698,
          0.32269207, -0.33102858],
        [-0.10247067,  0.53710549,  0.66707086, ..., -0.25118041,
         -0.16367395, -1.0032899 ],
        [-1.41752814,  0.98164928,  1.38217013, ...,  0.09677018,
         -0.24734983,  0.0724551 ],
        ...,
        [-1.39262175,  0.92081697, -0.20693936, ..., -1.25854632,
         -1.30114288,  0.61952652],
        [ 0.73438408, -0.72165533,  1.06434823, ..., -0.53060876,
         -0.59512769,  0.52806599],
        [ 1.09303611, -0.76844941,  1.85890297, ..., -0.46297642,
         -0.49053284, -0.61894421]]))

In [44]:
# Model Selection and Training
from sklearn.svm import LinearSVR
from sklearn.ensemble import RandomForestRegressor

# Models
svm_regression = LinearSVR(max_iter=10000, random_state=42)
rfr_regression = RandomForestRegressor(n_estimators=100, random_state=42)

# Training
svm_regression.fit(X_train_final, y_train)
rfr_regression.fit(X_train_final, y_train)

# Predictions
svm_pred = svm_regression.predict(X_test_final)
rfr_pred = rfr_regression.predict(X_test_final)

In [45]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Random Forest
rfr_mae = mean_absolute_error(y_test, rfr_pred)
rfr_mse = mean_squared_error(y_test, rfr_pred)
rfr_r2 = r2_score(y_test, rfr_pred)

print("Random Forest Regression:")
print("MAE:", rfr_mae)
print("MSE:", rfr_mse)
print("R2 Score:", rfr_r2)

print("----------------------------------")

# SVM
svm_mae = mean_absolute_error(y_test, svm_pred)
svm_mse = mean_squared_error(y_test, svm_pred)
svm_r2 = r2_score(y_test, svm_pred)

print("SVM Regression:")
print("MAE:", svm_mae)
print("MSE:", svm_mse)
print("R2 Score:", svm_r2)

Random Forest Regression:
MAE: 31622.461068313954
MSE: 2379638470.5106864
R2 Score: 0.8185823677743318
----------------------------------
SVM Regression:
MAE: 186833.86486708795
MSE: 48022380189.805405
R2 Score: -2.6611050862720576